Padms/1839
equinor/energyvision pull request #2016
Opened 2023-12-07 08:47 UTC by padms

2023-12-14 10:05 UTC, millianapia approved these changes
good purge

2023-12-18 11:54 UTC, fernandolucchesi requested changes
Left some comments, regarding the rollback changes, I think it is a better idea to work on it in a separate issue. Then we don't wait too long to get the other changes into production. (No need to revert code already modified, since it doesn't work anyways)

2023-12-18 11:54 UTC, fernandolucchesi commented on .devcontainer/devcontainer.json
> +  "postCreateCommand": "pnpm m i && (cd ./sanityv3 ; yarn install)",
sanity v3 uses pnpm, so we don't need the && cd blabla yarn install

2023-12-18 11:54 UTC, fernandolucchesi commented on package.json
> +    "setup-project": "pnpm m i && pnpm sanityv3 install",
pnpm m i will work for sanityv3. no need to run it twice

2023-12-18 11:54 UTC, fernandolucchesi commented on .github/workflows/PROD-studios-rollback.yaml
line 44, it is looking for studio-global image. I believe we have a different image name for v3

2023-12-18 11:54 UTC, fernandolucchesi commented on .github/workflows/PROD-studios-rollback.yaml
We should also have a rollback-secret job, similar to rollback global with secrets variables

2023-12-18 11:54 UTC, fernandolucchesi commented on .github/workflows/PROD-studios-rollback.yaml
it is probably a good idea to use the environment as a GH action input, allowing dev, preprod or prod.

2023-12-19 06:48 UTC, merged

2023-12-20 08:48 UTC, padms commented on .github/workflows/PROD-studios-rollback.yaml
No its studio-global only. Its the dev which is syudiov3-global-development