Text teaser component with themed background
equinor/energyvision pull request #2032
Opened 2024-01-03 11:01 UTC by padms

2024-01-16 11:30 UTC, fernandolucchesi requested changes
Looking nice @padms. Left some suggestion and few comments in the code.

2024-01-16 11:30 UTC, fernandolucchesi commented on sanityv3/schemas/objects/textTeaser.tsx
> +        input: function ({ onChange, value }: { onChange: any; value: string }) {
any on sanityv3 is bad... we should also refactor the RadioIconSelector...

`onChange: (event: PatchEvent) => void`

2024-01-16 11:30 UTC, fernandolucchesi commented on sanityv3/schemas/objects/textTeaser.tsx
> +        subtitle: blocksToText(text) || 'Mising teaser text',
Would recommentd prefixing the string 'Text Teaser | ' before adding subtitle content.. helps editors visualizing what section it is before going into the component. Also nice to add a media if you can find an interesting icon

2024-01-16 11:30 UTC, fernandolucchesi commented on web/lib/queries/common/pageContentFields.ts
> +  _type == "textTeaser" => {
extract into its own file as we did for the latest added components - so we have a readable/scalable groq in the future.

2024-01-16 11:30 UTC, fernandolucchesi commented on web/lib/queries/common/pageContentFields.ts
> +      "theme": coalesce(theme.value, 0),
Again, not a fan of the 0, especially when reading it like this (imagine you have no context of the component, is reading the query, and sees that default value is 0, you get not value from it)

2024-01-16 11:30 UTC, fernandolucchesi commented on web/pageComponents/shared/textTeaser/TextTeaser.tsx
> +type TitlePostion = 'left' | 'right' | undefined
undefined should not be an option

2024-01-16 11:30 UTC, fernandolucchesi commented on web/pageComponents/shared/textTeaser/TextTeaser.tsx
> +type TitlePostion = 'left' | 'right' | undefined
`"titlePosition": coalesce(titlePosition, 'left')`

2024-01-16 11:30 UTC, fernandolucchesi commented on web/pageComponents/shared/textTeaser/TextTeaser.tsx
> +  /* Hardcoded value while waiting for the w3c proposal for environment() */
what is this comment about?

2024-01-16 11:30 UTC, fernandolucchesi commented on web/pageComponents/shared/textTeaser/TextTeaser.tsx
> +  if ([title, text, action].every((i) => !i)) {
What is this for?

2024-01-16 11:30 UTC, fernandolucchesi commented on web/pageComponents/shared/textTeaser/TextTeaser.tsx
> +
somewhere in your styles an extra padding is being added to the last component:

<img width="621" alt="image" src="https://github.com/equinor/energyvision/assets/23337266/07492d83-518c-47d4-ad85-81d979ce0514">

2024-01-16 11:30 UTC, fernandolucchesi commented on web/types/types.ts
> +    titlePosition?: 'left' | 'right' | undefined
no need for undefined

2024-01-17 11:24 UTC, padms commented on sanityv3/schemas/components/ThemeSelector/defaultColors.ts
> +}
I tried to do something like this before, but couldn't think of naming when there are multiple highlight colors for a single component.. so made it simple

2024-01-18 13:23 UTC, fernandolucchesi approved these changes

2024-01-23 12:36 UTC, fernandolucchesi approved these changes

2024-01-29 11:24 UTC, merged