Refactor Teaser link to reuse in text teaser, key numbers components and anywhere else if any. #2066
equinor/energyvision pull request #2096
Opened 2024-02-02 13:30 UTC by millianapia

2024-02-05 06:18 UTC, padms requested changes
The ReadMoreLink can also be used in the 50-50 Hero Link

2024-02-06 13:22 UTC, millianapia commented
refactored the readmorelink so it could be used in more places

2024-02-12 13:33 UTC, BorghildSelle commented
You could do something like;
export type ReadMoreLinkProps = {
...
}  & Pick<LinkProps, 'variant'>

2024-02-20 14:17 UTC, BorghildSelle approved these changes

2024-02-21 09:07 UTC, merged