:sparkles: Create a new contact form for Equinor pension
equinor/energyvision pull request #2550
Opened 2024-10-07 06:30 UTC by VarunVAshrit

2024-10-14 09:38 UTC, padms requested changes
Minor clean up to be done. Otherwise looks good to me.

2024-10-14 09:38 UTC, padms commented on web/pages/api/forms/service-now-pension.ts
> +    console.log(catalogType)
Clean up this log

2024-10-14 12:19 UTC, VarunVAshrit commented on web/pages/api/forms/service-now-pension.ts
> +    console.log(catalogType)
Done

2024-10-14 13:59 UTC, padms approved these changes

2024-10-16 09:04 UTC, padms requested changes
There is something missing with the styles, the space around the form fields do not resemble the other forms

2024-10-18 07:43 UTC, BorghildSelle commented
This form will need to be updated to look similar with the other forms as in the #2510, 
so will try to get the other PR into main so this branch can merge in main and be updated

2024-11-05 12:41 UTC, merged