🔧 add workflow file for all studios and web #2672
equinor/energyvision pull request #2673
Opened 2024-11-12 15:04 UTC by millianapia

2024-11-15 06:37 UTC, VarunVAshrit approved these changes
LGTM

2024-12-06 08:05 UTC, padms requested changes
Deploy studios job deploys only secret studio 
Missing deploys to global and other satellite sites. 

Deploy all webs  only deploys global web.. satellite site deploy missing.

2024-12-20 10:03 UTC, padms commented
Deploy to backup cluster can be removed as we no longer use it.

2025-01-02 10:54 UTC, padms requested changes

2025-01-02 10:54 UTC, padms commented on .github/workflows/PROD-all-webs-and-studios.yaml
> +      - name: Deploy to Radix backup 🚀
Deploy to backup can be removed. There is a clean up task to remove app from backup cluster

2025-01-02 10:54 UTC, padms commented on .github/workflows/PROD-all-webs-and-studios.yaml
> +
Deploy Studios for satellites sites missing.

2025-03-10 12:57 UTC, merged