:sparkles: Add event dates support
equinor/energyvision pull request #616
Opened 2021-11-24 15:23 UTC by fernandolucchesi

A switch is used to change between events that have an exact start and end time, and events that do not.

![image](https://user-images.githubusercontent.com/23337266/143266026-ac904d07-9480-4fa7-baf8-5338938cb975.png)

![image](https://user-images.githubusercontent.com/23337266/143266062-e491f298-dec9-43a0-b0b8-0d0d360d828c.png)

![image](https://user-images.githubusercontent.com/23337266/143266149-5575202c-2187-461d-9648-6bebe3b6df19.png)

2021-11-25 09:51 UTC, wenche requested changes
Looks good! 👍  Nice work. 

Just try to add the workflow we talked about in the meeting :)

2021-11-25 09:51 UTC, wenche commented on studio/schemas/objects/eventDate.tsx
> +            return 'End date must be greater than start date'
Nice thing with an additional check here 👍

2021-11-25 09:51 UTC, wenche commented on studio/schemas/documents/event.ts
> +      title: 'Date information',
Not 100% sure if it needs to be a fieldset? 🤔  Might as well be without

2021-11-25 09:54 UTC, adneforslund approved these changes

2021-11-30 12:44 UTC, SvSven reviewed
Looks good to me. Just to double check: did we agree to not support multi-day events? Because that doesn't seem to be possible at the moment.

2021-11-30 12:44 UTC, SvSven commented on studio/schemas/objects/eventDate.tsx
> +      name: 'date',
I would add a short description where we also state the date format, just so it's clear at first glance

2021-12-01 07:32 UTC, fernandolucchesi commented
> Looks good to me. Just to double check: did we agree to not support multi-day events? Because that doesn't seem to be possible at the moment.

Hm that is what I understood from that meeting

2021-12-01 23:22 UTC, merged